### ISSUE TITLE
Do not show default confirmation screen when moving from one question to the next

### ISSUE THREAD

**Issue by wynnset** [tapestry-tool/tapestry-wp#1146]
If a user is doing an activity with multiple questions in it, when they submit a question, we always show them the confirmation screen with a button to continue to the next question. This can get quite annoying if the confirmation screen is always just saying "Thanks" and it also disrupts the flow for the user. For that reason, if a question doesn't have a customized confirmation screen, when they submit it we should take them directly to the next question. If it's the last question being submitted, we can show them the confirmation screen. 

Once the user clicks the continue button on the confirmation screen, we should take them back to the answer of the first question (currently it shows the answer to the last question)

In addition, whenever a question is submitted, we should immediately scroll the user back up to the top of the activity in multi-content context. Sometimes a question is long and when you submit it, it stays at the same scroll position on the page (which could be a content below) which is very confusing for the user.

**Comment by legendword** [comment]
There seems also to be an issue with submitting the second-to-last question and receive the answer view instead of the last question.
