### ISSUE TITLE
Disable Kaltura features when Kaltura not available in the backend

### ISSUE THREAD

**Issue by zifgu** [tapestry-tool/tapestry-wp#1238]
As @legendword noted in this discussion (https://github.com/tapestry-tool/tapestry-wp/pull/1215#discussion_r944683107), Kaltura video creation is still available in the NodeModal when Kaltura is disabled on the backend, and certain endpoints return nothing, which can be uninformative.

When Kaltura is disabled:
- Kaltura-related endpoints should throw a "Kaltura not available" error
- Users should not be able to create Kaltura videos or change other node types into Kaltura videos.
- Users should still be able to toggle "Use Kaltura Player" for videos that were already Kaltura videos. However, they will not be able to edit the fields (Kaltura ID and captions).

Note: This PR will likely need to be based off #1215 because it contains the latest changes to the VideoForm UI.

**Comment by wynnset** [comment]
Closed via #1239
