### ISSUE TITLE
Persist log of Kaltura uploads

### ISSUE THREAD

**Issue by zifgu** [tapestry-tool/tapestry-wp#1241]
In this feature, we want to start keeping a permanent record of past Kaltura uploads.

Changes to make:
- Change the existing upload log to be a permanent log. With each new upload, add entries to the end of the log instead of replacing it.
    - This means the same node can appear multiple times in the log (e.g. if uploaded unsuccessfully one or more times, or if the video was changed and re-uploaded).
~~- Add an option to the Settings modal to hide older completed uploads.~~
- Make upload log table paginated, and allow user to choose how many entries to show per page.

**Comment by wynnset** [comment]
Closed via PR #1243
