### ISSUE TITLE
Override default Kaltura account on individual sites

### ISSUE THREAD

**Issue by zifgu** [tapestry-tool/tapestry-wp#1247]
In multi-site (as well as potentially single-site) WordPress setups, owners of a particular site may wish to override the Kaltura configuration variables in `wp-config.php`, which apply to all sites, with a different Kaltura account.

- Add a new section under Settings > Tapestry admin page to enter a custom set of Kaltura credentials. 
- When determining whether Kaltura is enabled, creating Kaltura sessions, and passing variables to the frontend, look for a full set of 4 configuration variables in the overrided settings first. If one or more of the variables is not provided, then fall back to the default account in `wp-config`.

**Comment by wynnset** [comment]
Closed via PR #1248
